  version: '3.3'

  volumes:
       elk:

  services:

    elk:
      image: sebp/elk:623
      ports:
        - "5601:5601"
        - "9200:9200"
        - "5044:5044"
      volumes:
        - elk:/var/elk/data
      ulimits:
        nproc: 65536
        nofile:
          soft: 65536
          hard: 65536
      networks:
        - test

    server:
      build:
        context: ./server
        dockerfile: Dockerfile
        args:
          IBK_PROFILE: dev
      image: profile/server
      ports:
        - 8080:8080
      environment:
        SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}
      depends_on:
        - elk
      networks:
        - test

    client:
      build:
        context: ./client
        dockerfile: Dockerfile
        args:
          IBK_PROFILE: dev
      image: profile/client
      ports:
        - 8888:8888
      environment:
        SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}

      depends_on:
        - server
        - elk
      networks:
        - test

  networks:
    test:
      driver: bridge
